name: Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Docker Image
      id: docker_build
      run: |
        docker build -t pavangrandhi25/my_redis_git .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get latest version tag
      id: get_latest_tag
      run: |
        LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/pavangrandhi25/my_redis_git/tags/?page_size=1" | jq -r '.results[0].name // empty')
        echo "latest_tag=${LATEST_TAG}" >> $GITHUB_ENV

    - name: Increment version tag
      id: increment_tag
      run: |
        if [ -z "${{ env.latest_tag }}" ]; then
          NEXT_TAG="v1"
        else
          # Extract the version number from the latest tag and increment it
          VERSION_NUMBER=$(echo "${{ env.latest_tag }}" | sed 's/v//')
          NEXT_VERSION=$((VERSION_NUMBER + 1))
          NEXT_TAG="v${NEXT_VERSION}"
        fi
        echo "NEXT_TAG: $NEXT_TAG"
        echo "::set-output name=next_tag::$NEXT_TAG"

    - name: Push Docker Image
      run: |
        docker tag pavangrandhi25/my_redis_git:latest pavangrandhi25/my_redis_git:${{ steps.increment_tag.outputs.next_tag }}
        docker push pavangrandhi25/my_redis_git:${{ steps.increment_tag.outputs.next_tag }}
