name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image
      id: docker_build
      run: |
        docker build -t pavangrandhi25/my_redis_git .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'

    - name: Install semver
      run: |
        npm install -g semver
    
    - name: Install jq
      run: sudo apt-get install -y jq
    
    - name: Get latest version tag
      id: get_latest_tag
      run: |
        LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/pavangrandhi25/my_redis_git/tags/?page_size=1" | jq -r '.results[0].name // "v0"')
        echo "latest_tag=${LATEST_TAG}" >> $GITHUB_ENV

    - name: Increment version tag
      id: increment_tag
      run: |
        NEXT_TAG="${{ env.latest_tag }}"
        echo "NEXT_TAG before: $NEXT_TAG"
        if [ -z "$NEXT_TAG" ]; then
          NEXT_TAG="v1"
        elif [ "$NEXT_TAG" = "v0" ]; then
          NEXT_TAG="v1"
        else
          NEXT_TAG=$(semver bump patch $NEXT_TAG)
        fi
        echo "NEXT_TAG after: $NEXT_TAG"
        echo "::set-output name=next_tag::$NEXT_TAG"

    - name: Push Docker Image
      run: |
        docker tag pavangrandhi25/my_redis_git:latest pavangrandhi25/my_redis_git:${{ steps.increment_tag.outputs.next_tag }}
        docker push pavangrandhi25/my_redis_git:${{ steps.increment_tag.outputs.next_tag }}
    
    - name: Image Digest
      run: echo ${{ steps.docker_build.outputs.digest }}
